remote_theme: pages-themes/cayman@v0.2.0
title: Microsoft System Center / Support Scripts <br/> Service Manager
#show_downloads: false
#show_excerpts: false

#IMPORTANT: do NOT end the links below with a slash !
latestDownloadLink: https://github.com/microsoft/CSS-SystemCenter-ServiceManager/releases/latest/download
GitHubRepoLink: https://github.com/microsoft/CSS-SystemCenter-ServiceManager/tree/main
